sudo: required
services:
  - docker

language: elixir

elixir:
  - 1.7.3
otp_release:
  - 21.0.9

script:
  - mix do deps.get, compile
  - docker build -t myapp:release .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag "myapp:release" "navicore/myapp:latest";
    docker push "navicore/myapp:latest";
    docker tag "myapp:release" "navicore/myapp:0.1.$TRAVIS_BUILD_NUMBER";
    docker push "navicore/myapp:0.1.$TRAVIS_BUILD_NUMBER";
    fi

